### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by Thets48** [bym-refitted/backyard-monsters-refitted#20]
Some text still missing   #letter_word#

here few examples: 
![image](https://github.com/bym-refitted/backyard-monsters-refitted/assets/158123757/99852341-e7e3-4824-8b4a-e59631a5f69c)
![image](https://github.com/bym-refitted/backyard-monsters-refitted/assets/158123757/b6e6d76e-ce12-452a-9188-f00cec808985)
![image](https://github.com/bym-refitted/backyard-monsters-refitted/assets/158123757/cae9d826-3527-4282-94f3-5cb0d58a16ef)

Version: 0.2.3 Alpha

**Comment by React1-X** [comment]
Issue has been resolved, thanks. Closing this.
