### ISSUE TITLE
Purchase remaining resources with shiny does not reduce Shiny.

### ISSUE THREAD

**Issue by React1-X** [bym-refitted/backyard-monsters-refitted#21]
**How to reproduce:**
1. Click on 'Use Resources' when building or upgrading a building you don't have enough for.
2. A popup will appear asking if you want to purchase the needed resources with shiny to upgrade.
3. Shiny will not go down, and logs the following error:

`Cannot read properties of undefined (reading 'c')\n    at updateCredits`

**Comment by BigmanGHark** [comment]
Related to get better logs: https://github.com/bym-refitted/backyard-monsters-refitted/pull/24

**Comment by BigmanGHark** [comment]
Still seems there are some issues with this
