### ISSUE TITLE
Shiny doesn't decrease when no Internet connection is available.

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#26]
**Describe the bug**
If you have enough shiny to do any activity that requires shiny, you can prevent it from using shiny by disconnecting from the server.
_Anything bought from the shiny store works as intended even without connection._

**To Reproduce**
1. Load up your base
2. Pick anything that requires shiny to unlock/upgrade/speed up (where you have enough shiny)
3. Disconnect your connection (ie. wifi, unplug cable)
4. Do the upgrade

**Expected behavior**
Shiny to decrease or game to kick me out for losing connection.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Not in use
 - Using Flash Player: Yes. latest .swf file 0.2.3 Alpha

**Additional context**

**Comment by React1-X** [comment]
Closing this for now as a patch has just been applied to the client for detecting no connection to the server. It's pretty good for now, further measures on the server will likely reinforce this.

Thanks @W1GZY
