### ISSUE TITLE
Shiny doesn't decrease when you buy from the Monster Bunker store

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#37]
**Describe the bug**
You can buy monsters for your bunkers without spending any of your shiny.

**To Reproduce**
Open up monster bunker, click store, pick a monster you would like to have in your bunker and just buy it.

**Expected behavior**
deduction of shiny of the amount it costs

**Screenshots**
Before buying:
![monsterbunkerstore](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/4f54d387-51b5-47f1-8ee0-13e3a147a32b)
Successfully buying:
![monsterbunkerstore2](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/a89ffa80-0568-47e5-838d-1454c93ad2c1)
After closing the popup:
![monsterbunkerstore3](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/086c197b-6719-46f1-8782-861f55f43e66)

**Desktop (please complete the following information):**
 - OS: Winows
 - Using Flash Player 32.0

**Additional context**

**Comment by React1-X** [comment]
This has been fixed in a recent patch. Thanks. Closing this.
