### ISSUE TITLE
Sound button not working when left ON

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#39]
**Describe the bug**
The sound button _(Not to be mixed with music button)_ is not working as it is supposed to.
Everything is **OK** when it is muted and the game is  closed. The game will remember it is state (gray) and not play any sounds when the game is opened.
If the game is closed **WHILE** the sound button is ON (yellow), the game will remember it is state (yellow) and still not play any sounds when the game is opened.
Clicking it once while it is yellow will toggle the sounds ON, and still remain yellow and it will play sounds.

**To Reproduce**
Unmute sounds, close game.
Open game, the sounds button should be yellow but no sound should be heard.
Clicking it once will still let it remain yellow but play sounds.

**Expected behavior**
Play sounds when the toggle is left yellow and the game is re-opened.
Another option would be to revert to gray instead because sounds get muted after re-opening.

**Screenshots**
![image](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/fabca5d8-b2ef-4d65-8ebd-49f5af09179d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Using Flash Player yes

**Additional context**

**Comment by TheClassic0437** [comment]
I just fixed this bug. Turns out it was one leftover line in the SOUNDS.as file muting the game on start.

**Comment by React1-X** [comment]
> I just fixed this bug. Turns out it was one leftover line in the SOUNDS.as file muting the game on start.

Nice, yep just saw it now. This can be closed. Thanks.
