### ISSUE TITLE
Skipping Inferno attacks by closing the game

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#50]
**Describe the bug**
You are able to skip Inferno attacks by closing out the game. You will not take any damage and you can continue to upgrade and do whatever you want afterwards. You are skipping the Inferno cave stages with this too.

Does not apply to wild monster tribe  attacks.
**To Reproduce**
Start the game, if you are getting Inferno attack, close the game and reopen. Everything should be normal and no attack is happening. Inferno cavern gets bigger.

**Expected behavior**
if you close the game, the game should continue with the attack after reopening the game.

**Screenshots**
Opening the game first time
![infernoalert](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/0ef40c41-82bf-4e8e-a8e7-4b8766ff3a31)

Closing and opening the game second time
![infernoalert2](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/11e3d7b3-102e-493f-8e3f-f54885a5309c)

Inferno cavern expanding
![infernoalert3](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/5f854d2d-204b-4ee2-b123-f3ba53cb22b2)

**Desktop (please complete the following information):**
 - OS: Windows

 - Using Flash Player yes

**Comment by React1-X** [comment]
Closing this issue as it's from the original, and is probably way too much work than what it's worth. If people are skipping Inferno attacks in 2024 just to avoid some zagnoids, then that's their loss lol, as long as it doesn't break the game completely.
