### ISSUE TITLE
Log in screen breaks when window increased size

### ISSUE THREAD

**Issue by EvenBiggerManGhark** [bym-refitted/backyard-monsters-refitted#52]
**Describe the bug**
The thing isnt centered

**To Reproduce**
make your window big 

**Expected behavior**
It shouldnt break

**Screenshots**
![image](https://github.com/bym-refitted/backyard-monsters-refitted/assets/164915815/7b4e1d35-d952-48f8-beae-6f6c36f250fd)

**Desktop (please complete the following information):**
Probably all of them

**Additional context**
https://discord.com/channels/1126689848426774572/1225954831588528198

**Comment by React1-X** [comment]
Sorted
