### ISSUE TITLE
Clicking locked extra slots in Yard Planner soft locks the game

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#54]
**Describe the bug**
The extra slots soft locks the game when clicked on

**To Reproduce**
Open up Yard Planner
Click on Save Yard
Click on any of the locked saves

**Expected behavior**
Either show a pop up that is close able
OR
do nothing

**Screenshots**
Game being soft locked after clicking
![Screenshot_2](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/c54679eb-a523-4ce9-ba74-972b43238a7c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Using Flash Player Yes

**Additional context**
![Screenshot_1](https://github.com/bym-refitted/backyard-monsters-refitted/assets/96368352/75ebf698-29b8-4eca-ac8d-3411690b8609)

**Comment by React1-X** [comment]
Fixed in latest release.
