### ISSUE TITLE
(LINUX) Installer won't go past Downloading Flash Player

### ISSUE THREAD

**Issue by W1GZY** [bym-refitted/backyard-monsters-refitted#74]
**Describe the bug**
![image](https://github.com/user-attachments/assets/b29c76ae-7471-489e-b461-182b6f02e6ee)

POSSIBLY A USER ERROR. 
Check discord link below.

**To Reproduce**

**Expected behavior**
Install properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser 
 - Using Flash Player

**Additional context**
[Add any other context about the problem here.]
https://discord.com/channels/1126689848426774572/1300668772058927226

**Comment by React1-X** [comment]
@W1GZY - can we move this issue to our launcher repo [here](https://github.com/bym-refitted/bymr-desktop-launcher), and delete this one please? Thanks :)
