### ISSUE TITLE
Is there potential for dockerizing the server?

### ISSUE THREAD

**Issue by driftywinds** [bym-refitted/backyard-monsters-refitted#75]
Was wondering if this server can be made to run on a docker container?

**Comment by React1-X** [comment]
Hi @driftywinds 

Yes, this is being worked on #83 - and will be merged soon. Thanks!

**Comment by React1-X** [comment]
@driftywinds - closing, as this feature has now been merged! Thanks.

**Comment by driftywinds** [comment]
Thank you so much!
