### ISSUE TITLE
Cannot play Backyard Monsters Refitted:

### ISSUE THREAD

**Issue by DrFrankxio** [bym-refitted/backyard-monsters-refitted#76]
Yesterday:
![image](https://github.com/user-attachments/assets/22481497-a776-421b-9543-6204090434f7)
Today:
![image](https://github.com/user-attachments/assets/b9ec0f40-bbb6-4e32-9cb2-643a750de70d)
![image](https://github.com/user-attachments/assets/425a7164-2f8a-4de9-aaf5-50d38450c7c0)
Whats the reason to its making i cant connect to server?

**Comment by jlucaso1** [comment]
same here

**Comment by DrFrankxio** [comment]
Nah, another day without conection:
![image](https://github.com/user-attachments/assets/8fbfbaf4-281d-4e12-82ec-2651228caa2d)

**Comment by React1-X** [comment]
@jlucaso1 - Linux launcher issues are currently being fixed [here](https://github.com/bym-refitted/bymr-desktop-launcher/pull/8)

**Comment by React1-X** [comment]
@DrFrankxio - I'm assuming you are able to connect now? Am I good to close this issue?
