### ISSUE TITLE
The server starts showing save errors if I play around with shiny values or try to use the map room on my custom server

### ISSUE THREAD

**Issue by driftywinds** [bym-refitted/backyard-monsters-refitted#91]
I have installed the dockerized version of the server and it runs fine, but I wanted to know how I can play around with the values on phpMyAdmin to test stuff out
EDIT: - you go to "save"' and click on "edit"

**Comment by driftywinds** [comment]
Follow up question: - The server goes mental if I try to use the Map room and I can't do saves on my user after that. Is there a fix for that?

**Comment by React1-X** [comment]
@driftywinds - what value have you put for your shiny? Is it above the range of an integer?

It's better if we can discuss this issue on our discord instead.

**Comment by driftywinds** [comment]
> @driftywinds - what value have you put for your shiny? Is it above the range of an integer?
> 
> It's better if we can discuss this issue on our discord instead.

No, its something around 2 million which is not above the range of an integer. I shall DM you on discord!
